### ISSUE TITLE
A bug in turc

### ISSUE THREAD

**Issue by Koni2020** [phydrus/pyet#24]
The origin code for calculate evaporation according to [turc_1961]_ is as follow:
   c = tmean / tmean
   c[rh] = 1 - (50 - rh) / 70
   et = k * c * tmean / (tmean + 15) * (rs + 2.094)
   return et
However, there is a bug in c[rh] = 1 - (50 - rh) / 70. The correct code perhaps is  c[rh < 50] = 1 - (50 - rh) / 70 according to [turc_1961] based on Eq 3.

**Comment by mvremec** [comment]
Hi Koni,
Thank you for letting us know!  We really appreciate this!
This bug was actually noticed and is already fixed in the pyet_xarray branch. This branch is, however, not yet merged with the master branch. 
I will try to merge it with the master this weekend.
The new branch is also compatible with xarray, so this will be a major update.

There also seems to be a small mistake in your equation. The minus should actually be a +:
(see Turc(1961), Singh (2000) or Jensen (2016))
c[rh < 50] = 1 + (50 - rh) / 70

Thank you!

References:
Jensen et al., Task Committee on Revision of Manual 70. "Evaporation, evapotranspiration, and irrigation water requirements." American Society of Civil Engineers, 2016.
Xu, C‐Y., and V. P. Singh. "Evaluation and generalization of radiation‐based methods for calculating evaporation." Hydrological processes 14.2 (2000): 339-349.
